name: 'dml_dbt_platform'
version: '1.0.0'
config-version: 2

profile: 'dml_dbt_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  +docs:
    node_color: '#cd7f32'

models:
  dml_dbt_platform:
    staging:
      +materialized: view
      +schema: staging
      +docs:
        node_color: 'silver'
    marts:
      +materialized: table
      +schema: marts
      +docs:
        node_color: 'gold'
